apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: e2e32478
  namespace: default
spec:
  components:
        
          - name: e2e32478
            type: webservice
            properties:
              name: e2e32478
              image: healthidpuaeacr.azurecr.io/e2e32478:latest
              language: python
              framework: fastapi
              port: 8080
              healthPath: /health
              database: postgres
              appContainer: e2e32478
              exposeApi: true
